directory: /mnt/ssd0/music
library: /mnt/ssd0/music/musiclibrary.db
artist_credit: yes
plugins: fetchart lyrics musicbrainz

lyrics:
  auto: yes
  synced: yes

paths:
  singleton: $albumartist/Singles/$title
